---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  transformer_checkpoints_density: -1
  transformer_hidden_size: 512
  transformer_nhead: 8
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_transformer_block: 8
  max_time_step: 4096
  loss_context_warmup: 512
  memory_length: 512
  context_window: -1
  worldmodel_type: image
  image_decoder_type: regression
  image_decoder:
    diffusion_steps: 32


train_config:
  max_epochs: 15
  batch_size_vae: 1
  batch_size_causal: 1
  epoch_vae_stop: 2
  epoch_causal_start: 0
  time_step_vae: 256
  time_step_causal: 256
  learning_rate_vae: 1.0e-3
  learning_rate_causal: 1.0e-3
  learning_rate_vae_decay_interval: 1000
  learning_rate_causal_decay_interval: 1000
  vae_start_step: 0
  causal_start_step: 0
  data_path: ../../../data/maze_data_demo/
  load_model_path: ./checkpoints/pretrain_20240604_small
  save_model_path: ./checkpoints/
  master_port: "12345"
  max_save_iterations: 5000
  segment_length: 512
  evaluate_epochs: 1
  lossweight_policymodel: 0.40
  lossweight_worldmodel_raw: 0.40
  lossweight_worldmodel_latent: 0.20
  use_amp: True
  load_model_parameter_blacklist:
    - "attn_mask"

  sigma_scheduler: 1000
  sigma_value:
    - 0.0
    - 0.1
    - 0.2
    - 1.0

  lambda_scheduler: 1000
  lambda_value:
    - 0.0
    - 1.0e-7
    - 1.0e-6
    - 1.0e-5

test_config:
  batch_size: 1
  data_path: ../../../data/maze_data_demo/
  master_port: "12302"
  load_model_path: ./checkpoints/pretrain_20240604_small
  time_step: 2048
  segment_length: 256
  state_dropout: 0.0
  load_model_parameter_blacklist:
    - "attn_mask"

demo_config:
  master_port: "12313"
  time_step: 2030

  model_config:
    load_model_path: ./checkpoints/pretrain_20240621_small
    autoregressive_steps:
        - 1
        - 100
        - 1000
        - 2000
    autoregressive_length: 10
    policy:
      T_ini: 1.0
      T_dec: 0.001
      T_min: 0.4
    load_model_parameter_blacklist:
      - "attn_mask"
  maze_config:
    scale: 25
    density: 0.36
    n_landmarks: 8
  rule_config:
    mem_kr: 1.0
  run_model: 0
  run_rule: 1
  run_random: 0
  test_epochs: 1
  write_task: null
  read_task: null
  write_video: 1
  output: null
