---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  decision_checkpoints_density: 4
  decision_hidden_size: 768
  decision_inner_hidden_size: 1536
  decision_nhead: 16
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_decision_block: 18
  max_time_step: 16000
  max_segment_length: 2000
  loss_context_warmup: 500
  context_window: -1
  memory_length: 1000
  image_decoder_type: regression
  worldmodel_type: image
  causal_modeling: TRANSFORMER #/ PRNN / MAMBA
  image_decoder:
    diffusion_steps: 32


train_config:
  max_epochs: 50
  batch_size_vae: 1
  batch_size_causal: 1
  epoch_vae_stop: 2
  epoch_causal_start: 3
  time_step_vae: 16000
  time_step_causal: 16000
  learning_rate_vae: 2.0e-4
  learning_rate_causal: 5.0e-4
  learning_rate_vae_decay_interval: 1000
  learning_rate_causal_decay_interval: 1000
  vae_start_step: 50000
  causal_start_step: 50000
  segment_length: 1000
  data_path: "[PATH]"
  save_model_path: "./checkpoints"
  load_model_path: None
  master_port: "12300"
  max_save_iterations: 5000
  evaluate_epochs: 1
  lossweight_policymodel: 0.01
  lossweight_worldmodel_raw: 0.90
  lossweight_worldmodel_latent: 0.09
  lossweight_l2: 1.0e-6
  use_amp: False
  load_model_parameter_blacklist:
    - "lat_decoder"
    - "act_decoder"
    - "decformer"

  sigma_scheduler: 1000
  sigma_value:
    - 0.0
    - 0.1
    - 0.2
    - 1.0

  lambda_scheduler: 1000
  lambda_value:
    - 0.0
    - 1.0e-7
    - 1.0e-6
    - 1.0e-5

test_config:
  batch_size: 1
  data_path: "[PATH]"
  master_port: "12201"
  load_model_path: ""
  time_step: 16000
  segment_length: 1000

demo_config:
  master_port: "12211"
  time_step: 2048

  model_config:
    load_model_path: "[PATH]"
    autoregressive_steps:
        - 0
        - 100
        - 1000
        - 2000
    autoregressive_length: 10
    policy:
      T_ini: 1.0
      T_dec: 0.005
      T_min: 0.01
    load_model_parameter_blacklist:
      - "attn_mask"
  maze_config:
    scale: 15
    density: 0.36
    n_landmarks: 10
  rule_config:
    mem_kr: 1.0
  run_model: 0
  run_rule: 1
  run_random: 0
  task_file: "[PATH]"
  write_video: 0
  output: "[PATH]"
