---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  transformer_hidden_size: 1024
  transformer_nhead: 16
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_transformer_block: 24
  max_time_step: 1024
  loss_context_warmup: 256
  image_decoder_type: regression
  image_decoder:
    diffusion_steps: 32

train_config:
  batch_size: 1

evaluate_config:
  batch_size: 1
  policy:
    softmax: 0.80
    greedy: 0.20
