---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  transformer_checkpoints_density: 4
  transformer_hidden_size: 1280
  transformer_nhead: 16
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_transformer_block: 12
  max_time_step: 2048
  loss_context_warmup: 512
  context_free: -1
  image_decoder_type: regression
  worldmodel_type: image
  image_decoder:
    diffusion_steps: 32


train_config:
  max_epochs: 15
  batch_size_vae: 1
  batch_size_causal: 1
  epoch_vae_stop: -1
  epoch_causal_start: -1
  time_step_vae: 256
  time_step_causal: 256
  learning_rate_vae: 1.0e-3
  learning_rate_causal: 1.0e-3
  learning_rate_vae_decay_interval: 1000
  learning_rate_causal_decay_interval: 1000
  vae_start_step: 0
  causal_start_step: 0
  data_path: "[PATH]"
  load_model_path: "[PATH]"
  save_model_path: "[PATH]"
  master_port: "12300"
  max_save_iterations: 5000
  evaluate_epochs: 1
  lossweight_policymodel: 0.1
  lossweight_worldmodel_raw: 0.85
  lossweight_worldmodel_latent: 0.05
  use_amp: False
  load_model_parameter_blacklist:
    - "lat_decoder"
    - "act_decoder"
    - "decformer"

  sigma_scheduler: 1000
  sigma_value:
    - 0.0
    - 0.1
    - 0.2
    - 1.0

  lambda_scheduler: 1000
  lambda_value:
    - 0.0
    - 1.0e-7
    - 1.0e-6
    - 1.0e-5

test_config:
  batch_size: 1
  data_path: "[PATH]"
  master_port: "12201"
  load_model_path: "[PATH]"
  time_step: 512
  segment_length: 512

demo_config:
  master_port: "12211"
  time_step: 2048

  model_config:
    load_model_path: "[PATH]"
    autoregressive_threshold: 128
    autoregressive_interval: 8
    policy:
      greedy_init: 0.0
      greedy_increment: 0.001
      greedy_max: 0.75
  maze_config:
    scale: 25
    density: 0.36
    n_landmarks: 8
  rule_config:
    mem_kr: 1.0
  run_model: 0
  run_rule: 1
  run_random: 0
  test_epochs: 1
  write_task: null
  read_task: null
  output: "[PATH]"
