---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  transformer_checkpoints_density: 4
  transformer_hidden_size: 1024
  transformer_nhead: 16
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_transformer_block: 24
  max_time_step: 1024
  loss_context_warmup: 256
  image_decoder_type: regression
  image_decoder:
    diffusion_steps: 32


train_config:
  max_epochs: 15
  batch_size_vae: 1
  batch_size_causal: 1
  epoch_vae_stop: -1
  epoch_causal_start: -1
  time_step_vae: 256
  time_step_causal: 256
  learning_rate_vae: 1.0e-3
  learning_rate_causal: 1.0e-3
  learning_rate_vae_decay_interval: 1.0e-3
  learning_rate_causal_decay_interval: 1000
  data_path: ../../../data/maze_data_demo/
  load_model_path: ./checkpoints/pretrain_35_20240513
  save_model_path: ./checkpoints/
  master_port: "12300"
  max_save_iterations: 5000
  evaluate_epochs: 1
  lossweight_policymodel: 0.40
  lossweight_worldmodel_raw: 0.40
  lossweight_worldmodel_latent: 0.20
  use_amp: True
  load_model_parameter_blacklist:
    - "lat_decoder"
    - "act_decoder"
    - "decformer"

  sigma_scheduler: 1000
  sigma_value:
    - 0.0
    - 0.1
    - 0.2
    - 1.0

  lambda_scheduler: 1000
  lambda_value:
    - 0.0
    - 1.0e-7
    - 1.0e-6
    - 1.0e-5

test_config:
  batch_size: 1
  data_path: ../../../data/maze_data_demo/
  master_port: "12301"
  load_model_path: ./checkpoints/pretrain_35_20240513
  time_step: 1024

demo_config:
  master_port: "12301"
  policy:
    softmax: 0.80
    greedy: 0.20

  model_config:
    batch_size: 1
    data_path: ../../../data/maze_data_demo/
    master_port: "12301"
    load_model_path: ./checkpoints/pretrain_35_20240513
  time_step: 1024
  maze_config:
    scale: 25
    density: 0.36
    n_landmarks: 8
  rule_config:
    mem_kr: 1.0
  run_model: 0
  run_rule: 1
  run_random: 0
  test_epochs: 1
  write_task: null
  read_task: null
  output: ./videos
