---
model_config:
  image_size: 128
  action_size: 5
  map_size: 7
  transformer_hidden_size: 1024
  transformer_nhead: 16
  image_latent_size: 1024
  image_encoder_size: 384
  n_residual_block: 2
  n_transformer_block: 24
  max_time_step: 1024
  loss_context_warmup: 256
  image_decoder_type: regression
  image_decoder:
    diffusion_steps: 32


train_config:
  batch_size_vae: 1
  batch_size_causal: 1
  epoch_vae_stop: -1
  epoch_causal_start: -1
  time_step_vae: 1024
  time_step_causal: 1024
  learning_rate_vae: 1.0e-3
  learning_rate_causal: 1.0e-3
  learning_rate_vae_decay_interval: 1.0e-3
  learning_rate_causal_decay_interval: 1000
  data_path: ./data
  load_model_path: ./checkpoints/01
  save_model_path: ./checkpoints/
  master_port: "12300"

test_config:
  batch_size: 1
  time_step: 1024
  data_path: ./data
  master_port: "12301"
  load_model_path: ./checkpoints/01

demo_config:
  load_model_path: ./checkpoints/01
  master_port: "12301"
  policy:
    softmax: 0.80
    greedy: 0.20
